version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: pharmacy_pos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pharmacy_pos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pharmacy_network

  redis:
    image: redis:7-alpine
    container_name: pharmacy_pos_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pharmacy_network

volumes:
  postgres_data:
  redis_data:

networks:
  pharmacy_network:
    driver: bridge
